### ISSUE TITLE
Special characters in code break API

### ISSUE THREAD

**Issue by aleho** [webgriffe/SyliusAkeneoPlugin#51]
While I'm not especially fond of special characters in an SKU, if customer requires it they shouldn't break API calls nevertheless.

Currently, an SKU `123#456` will fail:

```
Client error: `GET http://pim/api/rest/v1/products/123#456` resulted in a `404 Not Found` response:
{"code":404,"message":"Product \"123\" does not exist or you do not have permission to access it."}
```

Solution might be to simply `urlencode()` each code or, even better, use the official client.

Is there a plan to switch to it or should I provide a PR for the current implementation?

**Comment by mmenozzi** [comment]
Hi @aleho,
yes is there a plan to switch to the official Akeneo client. This has been done already in #20 but it has many BC break. If you want you can continue that PR to remove all the BC breaks.

Otherwise if you need this bug fixed sooner feel free to provide a PR for the current implementation.
